### ISSUE TITLE
Unable to input iscell.npy files while importing suite2p data

### ISSUE THREAD

**Issue by harinisuri** [RichieHakim/ROICaT#317]
Hello,

I am trying to track the same neurons across multiple sessions using data already processed with suite2p. I would like to only track the neurons already classified as "is cell" by suite2p. I see from the code that I can give the iscell.npy files as inputs to the roicat.data_importing.Data_suite2p function but when I do that, it gives me a TypeError. 

Here is my code snippet - 
#--------------------------------
#Defining data paths 
dir_allOuterFolders = 'Z:/Harini/AllTestingSamples/RegTesting/'
pathSuffixToStat = 'stat.npy'
pathSuffixToOps = 'ops.npy'
pathSuffixToIsCell = 'iscell.npy'

paths_allStat = roicat.helpers.find_paths(
    dir_outer=dir_allOuterFolders,
    reMatch=pathSuffixToStat,
    depth=6,
)[:]
paths_allOps  = np.array([Path(path).resolve().parent / pathSuffixToOps for path in paths_allStat])[:]
paths_allIsCell  = np.array([Path(path).resolve().parent / pathSuffixToIsCell for path in paths_allStat])[:]

print(f'paths to all stat files:');
[print(path) for path in paths_allStat];
print('');
print(f'paths to all ops files:');
[print(path) for path in paths_allOps];
print('');
print(f'paths to all iscell files:');
[print(path) for path in paths_allIsCell];

#-------------------------------------------
##IMPORT DATA
data = roicat.data_importing.Data_suite2p(
    paths_statFiles=paths_allStat[:],
    paths_opsFiles=paths_allOps[:],    
    paths_iscell=paths_allIsCell[:], #DOES NOT WORK!
    um_per_pixel=2.7,  ## IMPORTANT PARAMETER. Use a list of floats if values differ in each session. ## Get this value from data acquisition 
    new_or_old_suite2p='new',
    type_meanImg='meanImg', #can be meanImgE as well
    verbose=True,
)

And here is the error - 
![image](https://github.com/user-attachments/assets/b4eee667-cade-46cf-8ac1-7fd0b47f248f)

**Comment by RichieHakim** [comment]
Thank you for posting this issue. I want to make sure that this works more smoothly for you and others. 

I just tried to recreate the error and was not able to. The error suggests that the arg 'paths_iscell' is not available in the version of the `roicat` library you are using. So, I suspect you are using an older version where the `Data_suite2p` class doesn't have a `paths_iscell` argument input.

1. Please check which version of `roicat` you have using:
```
roicat.__version__
```
and if it is not up to date (current release version is 1.2.2), please upgrade it using the following terminal command:
```
pip install --upgrade roicat[all]
```

2. Reconsider **only** tracking ROIs where iscell==True. I recommend tracking **all** ROIs against each other, then subsequently using inclusion criteria to remove bad clusters as well as bad ROIs from clusters. I just wrote a new notebook (currently only on the 'dev' branch of the repo) on how to mask out good ROIs after tracking: https://github.com/RichieHakim/ROICaT/blob/2244fd12db3a174ac6a558116edeb4cffbd1c347/notebooks/jupyter/tracking/3_tracking_handling_outputs.ipynb

3. A big change to the codebase with many updates is going to be released in the next couple days. Your desire to track only good ROIs is a common desire and currently it is not supported natively, so I will prioritize adding support for that. Simply importing the iscell.npy file into the Data_suite2p object will not restrict tracking to good ROIs. Currently, the best way to do it is to make a custom `Data_roicat` object using the following approach based on some things you can learn about in the [demo_data_importing](https://github.com/RichieHakim/ROICaT/blob/main/notebooks/jupyter/other/demo_data_importing.ipynb) notebook:
```
## Make a data object 
data_tmp = roicat.data_importing.Data_suite2p(
    paths_statFiles=paths_allStat,
    paths_opsFiles=paths_allOps,
    paths_iscell=paths_iscell,
    um_per_pixel=1.0,
)

data = roicat.data_importing.Data_roicat()
data.set_spatialFootprints(
    spatialFootprints=[sf[c==1] for sf, c in zip(data_tmp.spatialFootprints, data_tmp.class_labels_index)],
    um_per_pixel=data.um_per_pixel,
)
data.set_FOV_images(FOV_images=data_tmp.FOV_images)
data.transform_spatialFootprints_to_ROIImages()

assert data.check_completeness(verbose=False)['tracking'], f"Data object is missing attributes necessary for tracking."
```

I will write in the ability to track only ROIs with a certain class label (like iscell==1) right now and try to push the new updates to PyPI by the end of the day. Note however that there are significant updates to how file outputs are saved.

Also, if you'd like to just zoom and chat about this briefly, let me know by email (at the address you can find in my github profile).

**Comment by RichieHakim** [comment]
I forgot to mention, this is a working repository and we have not yet published this approach (hopefully this happens very soon). Until then, we ask that if you do end up wanting to publish using this method prior to our manuscript being out that we chat very briefly about attribution.

----

Changes are pushed to main branch and PyPI now (v1.3). Commit with changes: https://github.com/RichieHakim/ROICaT/commit/47023e1fb0a72e807abb0a1939b8614b20ab5b19

You can now call:
```
data.remove_rois_by_classLabel(classLabel_to_keep=1)
```
to remove ROIs within a data object according to their class label. When importing a suite2p iscell.npy file, the labels are 0 and 1. In the above example, it will remove all ROIs with label==1.

You can upgrade ROICaT by fetching a new version of the repository files and then upgrading the library. Instructions for upgrading are on the new Readme page.

Note that the new version of ROICaT uses a different file type and structure for output results files. Let me know if you have any trouble or just want to chat about your specific use case. Good luck!

**Comment by RichieHakim** [comment]
Good to hear. To be clear, I just pushed all the updates yesterday, so the package is actually in a stable place right now

**Comment by RichieHakim** [comment]
@mkzhou00 
> Hi Richie, I'm currently facing the same issue, although I'm using the current Roicat version, which is 1.5.1. Do you have any ideas why?

Hi, could you give me some more information on what is going wrong (or fill out a new issue)?

I'll assume you mean that you are getting an error saying that the argument 'paths_iscell' is unexpected. This issue seemed to be resolved for Harini by updating to the new version, which *does* have the paths_iscell argument:
https://github.com/RichieHakim/ROICaT/blob/444eabb98d887bc83d338a353e1b3e66b30757ad/roicat/data_importing.py#L1038
If you are using v1.5.1, then this error is unlikely.
