### ISSUE TITLE
[BUG]: Issue saving richfiles

### ISSUE THREAD

**Issue by dyf** [RichieHakim/ROICaT#324]
### Describe the bug

I was running the example tracking notebook and trying to save richfiles, ran into this error: 
```
Exception ignored in: <function FileLock_AutoDeleting.__del__ at 0x7f3c513efd00>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/richfile/util.py", line 1119, in __del__
    self.release(force=False)
  File "/opt/conda/lib/python3.10/site-packages/richfile/util.py", line 1106, in release
    super().release(force=force)
  File "/opt/conda/lib/python3.10/site-packages/filelock/_api.py", line 280, in release
    if self.is_locked:
  File "/opt/conda/lib/python3.10/site-packages/filelock/_api.py", line 190, in is_locked
    return self._context.lock_file_fd is not None
AttributeError: 'FileLock_AutoDeleting' object has no attribute '_context'
Traceback (most recent call last):
  File "/code/run_capsule.py", line 39, in <module>
    if __name__ == "__main__": run()
  File "/code/run_capsule.py", line 23, in run
    results = align_plane(plane, '/results', str(name))
  File "/code/tracking.py", line 308, in align_plane
    roicat.util.RichFile_ROICaT(path=paths_save['results_all']).save(obj=results_all, overwrite=True)
  File "/opt/conda/lib/python3.10/site-packages/richfile/util.py", line 659, in save
    with SafeSaver(
  File "/opt/conda/lib/python3.10/site-packages/richfile/util.py", line 1308, in __init__
    self.lock = FileLock_AutoDeleting(
TypeError: FileLock_AutoDeleting.__init__() got an unexpected keyword argument 'force'
```

### Versions + System info

{ 'datetime': '2024-10-04 17:25:37', 'roicat': {'version': '1.3.0', 'date_installed': 'Fri Oct  4 17:25:33 2024'}, 'operating_system': {'libc_ver': ('glibc', '2.35'), 'win32_is_iot': False, 'win32_edition': None, 'win32_ver': ('', '', '', ''), 'mac_ver': ('', ('', '', ''), ''), 'java_ver': ('', '', ('', '', ''), ('', '', '')), 'system_alias': None, 'architecture': ('64bit', ''), 'uname_result': None, 'uname': uname_result(system='Linux', node='810a2a0b7948', release='4.14.350-266.564.amzn2.x86_64', version='#1 SMP Sat Aug 10 09:56:03 UTC 2024', machine='x86_64'), 'system': 'Linux', 'node': '810a2a0b7948', 'release': '4.14.350-266.564.amzn2.x86_64', 'version': '#1 SMP Sat Aug 10 09:56:03 UTC 2024', 'machine': 'x86_64', 'processor': 'x86_64', 'python_implementation': 'CPython', 'python_version': '3.10.12', 'python_version_tuple': ('3', '10', '12'), 'python_branch': '', 'python_revision': '', 'python_build': ('main', 'Jun 23 2023 22:40:32'), 'python_compiler': 'GCC 12.3.0', 'platform': 'Linux-4.14.350-266.564.amzn2.x86_64-x86_64-with-glibc2.35', 'freedesktop_os_release': {'NAME': 'Ubuntu', 'ID': 'ubuntu', 'PRETTY_NAME': 'Ubuntu 22.04.2 LTS', 'VERSION_ID': '22.04', 'VERSION': '22.04.2 LTS (Jammy Jellyfish)', 'VERSION_CODENAME': 'jammy', 'ID_LIKE': 'debian', 'HOME_URL': 'https://www.ubuntu.com/', 'SUPPORT_URL': 'https://help.ubuntu.com/', 'BUG_REPORT_URL': 'https://bugs.launchpad.net/ubuntu/', 'PRIVACY_POLICY_URL': 'https://www.ubuntu.com/legal/terms-and-policies/privacy-policy', 'UBUNTU_CODENAME': 'jammy'}}, 'cpu_info': {'n_cores': 16, 'brand': 'Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz'}, 'user': 'root', 'ram': svmem(total=66698895360, available=64317730816, percent=3.6, used=1643089920, free=46798802944, active=1370816512, inactive=16710766592, buffers=3907584, cached=18253094912, shared=983040, slab=1254715392), 'gpu_info': {0: {'id': 0, 'uuid': 'GPU-342409fa-6f51-6144-eb25-27eeaab12f1b', 'load': 0.0, 'memoryUtil': 0.00013020833333333333, 'memoryTotal': 15360.0, 'memoryUsed': 2.0, 'memoryFree': 14926.0, 'driver': '525.105.17', 'name': 'Tesla T4', 'serial': '1325021038908', 'display_mode': 'Enabled', 'display_active': 'Disabled', 'temperature': 23.0}}, 'conda_env': 'base', 'python': '3.10.12', 'gcc': '11.4.0', 'torch': '2.4.1+cu121', 'cuda': '12.1', 'cudnn': 90100, 'torch_devices': ['device 0: Name=Tesla T4, Memory=15.653470208 GB'], 'pkgs': {'brotli': '1.0.9', 'pysocks': '1.7.1', 'cffi': '1.15.1', 'charset-normalizer': '3.2.0','colorama': '0.4.6', 'conda': '23.1.0', 'conda-package-handling': '2.0.2', 'conda_package_streaming': '0.8.0', 'cryptography': '41.0.2', 'idna': '3.4', 'libmambapy': '1.4.2', 'mamba': '1.4.2', 'pip': '23.1.2', 'pyopenssl': '23.2.0', 'pycosat': '0.6.4', 'pycparser': '2.21', 'requests': '2.31.0', 'ruamel.yaml': '0.17.32', 'ruamel.yaml.clib': '0.2.7', 'setuptools': '68.0.0', 'toolz': '0.12.0', 'urllib3': '2.0.3', 'wheel': '0.40.0', 'zstandard': '0.19.0', 'asciitree': '0.3.3', 'dill': '0.3.9','fasteners': '0.19', 'hdmf': '3.14.4', 'lazy-ops': '0.2.0', 'numcodecs': '0.13.0', 'pynwb': '2.8.2', 'roiextractors': '0.5.7', 'zarr': '2.18.3', 'gputil': '1.4.0', 'mako': '1.3.5', 'markdown': '3.7', 'pint': '0.24.3', 'pyyaml': '6.0.2', 'sqlalchemy': '2.0.35', 'aind-data-schema': '1.0.0', 'aind-data-schema-models': '0.5.5', 'aind-metadata-upgrader': '0.0.20', 'alembic': '1.13.3', 'annotated-types': '0.7.0', 'appdirs': '1.4.4', 'arrow': '1.3.0', 'attrs': '24.2.0', 'backports-datetime-fromisoformat': '2.0.1', 'bokeh': '3.5.2', 'colorcet': '3.1.0', 'coloredlogs': '15.0.1', 'colorlog': '6.8.2', 'configparser': '7.1.0', 'contourpy': '1.3.0', 'cycler': '0.12.1', 'dictdiffer': '0.9.0', 'flatbuffers': '24.3.25', 'flexcache': '0.3', 'flexparser': '0.3.1', 'fonttools': '4.54.1', 'fqdn': '1.5.1', 'fsspec': '2024.9.0', 'greenlet': '3.1.1', 'h11': '0.14.0', 'h5py': '3.12.1', 'hdbscan': '0.8.38.post1', 'holoviews': '1.19.1', 'humanfriendly': '10.0', 'inflection': '0.5.1', 'iniconfig': '2.0.0', 'isoduration': '20.11.0', 'joblib': '1.4.2', 'jsonpointer': '3.0.0', 'jupyter_bokeh': '4.0.5', 'kiwisolver': '1.4.7', 'kymatio': '0.3.0', 'linkify-it-py': '2.0.3', 'llvmlite': '0.43.0', 'markdown-it-py': '3.0.0', 'mat73': '0.65', 'matplotlib': '3.9.2', 'mdit-py-plugins': '0.4.2', 'mdurl': '0.1.2', 'natsort': '8.4.0', 'numba': '0.60.0', 'numpy': '2.0.2', 'nvidia-cublas-cu12': '12.1.3.1', 'nvidia-cuda-cupti-cu12': '12.1.105', 'nvidia-cuda-nvrtc-cu12': '12.1.105', 'nvidia-cuda-runtime-cu12': '12.1.105', 'nvidia-cudnn-cu12': '9.1.0.70', 'nvidia-cufft-cu12': '11.0.2.54', 'nvidia-curand-cu12': '10.3.2.106', 'nvidia-cusolver-cu12': '11.4.5.107', 'nvidia-cusparse-cu12': '12.1.0.106', 'nvidia-nccl-cu12': '2.20.5', 'nvidia-nvjitlink-cu12': '12.6.77', 'nvidia-nvtx-cu12': '12.1.105', 'onnx': '1.17.0', 'onnx2torch': '1.5.15', 'onnxconverter-common': '1.14.0', 'onnxruntime': '1.19.2', 'opencv-contrib-python-headless': '4.10.0.84', 'optuna': '4.0.0', 'outcome': '1.3.0.post0', 'pandas': '2.2.3', 'panel': '1.5.2', 'param': '2.1.1', 'pillow': '10.4.0', 'plotly': '5.24.1', 'pluggy': '1.5.0', 'protobuf': '3.20.2', 'psutil': '6.0.0', 'py-cpuinfo': '9.0.0', 'pydantic': '2.8.2', 'pydantic_core': '2.20.1', 'pynndescent': '0.5.13', 'pyparsing': '3.1.4', 'pytest': '8.3.3', 'pyviz_comms': '3.0.3', 'richfile': '0.4.3', 'roicat': '1.3.0', 'scikit-learn': '1.5.2', 'scipy': '1.14.1', 'seaborn': '0.13.2', 'selenium': '4.25.0', 'semver': '3.0.2', 'skl2onnx': '1.17.0', 'sortedcontainers':'2.4.0', 'sparse': '0.15.4', 'tenacity': '9.0.0', 'threadpoolctl': '3.5.0', 'torch': '2.4.1', 'torchaudio': '2.4.1', 'torchvision': '0.19.1', 'tqdm': '4.66.5', 'trio': '0.26.2', 'trio-websocket': '0.11.1', 'triton': '3.0.0', 'types-python-dateutil': '2.9.0.20241003', 'typing_extensions': '4.12.2', 'tzdata': '2024.2', 'uc-micro-py': '1.0.3', 'umap-learn': '0.5.6', 'uri-template': '1.3.0', 'webcolors': '24.8.0', 'websocket-client': '1.8.0', 'wsproto': '1.2.0', 'xxhash': '3.5.0', 'xyzservices': '2024.9.0', 'filelock': '3.13.1', 'gmpy2': '2.1.2', 'mpmath': '1.3.0', 'networkx': '3.2.1', 'sympy': '1.12', 'babel': '2.12.1', 'jinja2': '3.1.2', 'markupsafe': '2.1.3', 'pyqt5': '5.15.7', 'pyqt5-sip': '12.11.0', 'pygments': '2.15.1', 'qtpy': '2.3.1', 'send2trash': '1.8.2', 'aiofiles': '22.1.0', 'aiosqlite': '0.19.0', 'anyio': '3.7.1', 'argon2-cffi': '21.3.0', 'argon2-cffi-bindings': '21.2.0', 'asttokens': '2.2.1', 'backcall': '0.2.0', 'backports.functools-lru-cache': '1.6.5', 'beautifulsoup4': '4.12.2', 'bleach': '6.0.0', 'certifi': '2023.7.22', 'comm': '0.1.3', 'debugpy': '1.6.7', 'decorator': '5.1.1', 'defusedxml': '0.7.1', 'entrypoints': '0.4', 'exceptiongroup': '1.1.2', 'executing': '1.2.0', 'fastjsonschema': '2.18.0', 'flit_core': '3.9.0', 'importlib-metadata': '6.8.0', 'importlib-resources': '6.0.0', 'ipykernel': '6.24.0', 'ipython': '8.14.0', 'ipython-genutils': '0.2.0', 'ipywidgets': '8.0.7', 'jedi': '0.18.2', 'json5': '0.9.14', 'jsonschema': '4.18.4', 'jsonschema-specifications': '2023.7.1', 'jupyter': '1.0.0', 'jupyter_client': '8.3.0', 'jupyter-console': '6.6.3', 'jupyter_core': '5.3.1', 'jupyter-events': '0.6.3', 'jupyter_server': '2.7.0', 'jupyter_server_fileid': '0.9.0', 'jupyter_server_terminals': '0.4.4', 'jupyter_server_ydoc': '0.8.0', 'jupyter-ydoc': '0.2.4', 'jupyterlab': '3.6.2', 'jupyterlab-pygments': '0.2.2', 'jupyterlab_server': '2.24.0', 'jupyterlab-widgets': '3.0.8', 'matplotlib-inline': '0.1.6', 'mistune': '3.0.0', 'nbclassic': '1.0.0', 'nbclient': '0.8.0', 'nbconvert': '7.7.2', 'nbformat': '5.9.1', 'nest-asyncio': '1.5.6', 'notebook': '6.5.4', 'notebook_shim': '0.2.3', 'overrides': '7.3.1', 'packaging': '23.1', 'pandocfilters': '1.5.0', 'parso': '0.8.3', 'pexpect': '4.8.0', 'pickleshare': '0.7.5', 'pkgutil_resolve_name': '1.3.10', 'platformdirs': '3.9.1', 'ply': '3.11', 'prometheus-client': '0.17.1', 'prompt-toolkit': '3.0.39', 'ptyprocess': '0.7.0', 'pure-eval': '0.2.2', 'python-dateutil': '2.8.2', 'python-json-logger': '2.0.7', 'pytz': '2023.3', 'pyzmq': '25.1.0', 'qtconsole': '5.4.3', 'referencing': '0.30.0', 'rfc3339-validator': '0.1.4', 'rfc3986-validator': '0.1.1', 'rpds-py': '0.9.2', 'sip': '6.7.9', 'six': '1.16.0', 'sniffio': '1.3.0', 'soupsieve': '2.3.2.post1', 'stack-data': '0.6.2', 'terminado': '0.17.1', 'tinycss2': '1.2.1', 'toml': '0.10.2', 'tomli': '2.0.1', 'tornado': '6.3.2', 'traitlets': '5.9.0', 'typing-utils': '0.1.0', 'wcwidth': '0.2.6', 'webencodings': '0.5.1', 'widgetsnbextension': '4.0.8', 'y-py': '0.5.9', 'ypy-websocket': '0.8.2', 'zipp': '3.16.2'}}

**Comment by dyf** [comment]
I'm also trying to use the legacy methods to save `run_data`, getting the following:

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[39], line 9
      2 roicat.helpers.pickle_save(
      3     obj=results_all,
      4     filepath=path_save,
      5     mkdir=True,
      6 )
      8 path_save = paths_save['run_data']
----> 9 roicat.helpers.pickle_save(
     10     obj=run_data,
     11     filepath=path_save,
     12     mkdir=True,
     13 )

File /opt/conda/lib/python3.10/site-packages/roicat/helpers.py:1578, in pickle_save(obj, filepath, mode, zipCompress, mkdir, allow_overwrite, **kwargs_zipfile)
   1576 else:
   1577     with open(path, mode) as f:
-> 1578         pickle.dump(obj, f)

File /opt/conda/lib/python3.10/site-packages/torch/utils/data/dataloader.py:653, in _BaseDataLoaderIter.__getstate__(self)
    647 def __getstate__(self):
    648     # TODO: add limited pickling support for sharing an iterator
    649     # across multiple threads for HOGWILD.
    650     # Probably the best way to do this is by moving the sample pushing
    651     # to a separate thread and then just sharing the data queue
    652     # but signalling the end is tricky without a non-blocking API
--> 653     raise NotImplementedError("{} cannot be pickled", self.__class__.__name__)

NotImplementedError: ('{} cannot be pickled', '_MultiProcessingDataLoaderIter')
```

**Comment by RichieHakim** [comment]
Thank you for the bug report. I'm sorry for the issues. These are both easy fixes.

Quick fixes you can do on your own if you just want results now:
Issue 1) Update to python 3.10.
Issue 2) Uncomment the first @property method in roicat.util to make a serializable_dict, then make a serializable dict to save using the pickle_save function:
```
run_data_sd = {
    'data': data.serializable_dict,
    'aligner': aligner.serializable_dict,
    'blurrer': blurrer.serializable_dict,
    'roinet': roinet.serializable_dict,
    'swt': swt.serializable_dict,
    'sim': sim.serializable_dict,
    'clusterer': clusterer.serializable_dict,
}
roicat.helpers.pickle_save(
    obj=run_data_sd,
    filepath=str(dir_save / (name_save + '.ROICaT.tracking.rundata' + '.pkl')),
    mkdir=True,
)
```

Details:
**Issue 1: the richfile / filelock issue**
You are on python=3.10, I stopped supporting python<3.11 in my CI testing because it is out of [bug support](https://devguide.python.org/versions/) and there are some syntax things that were introduced in 3.11 that I use. **I will attempt to bring back support for python=3.10 if you'd like** and I will also add a `'python_requires'` kwarg in the setup.py file so that this doesn't happen again. After trying out 3.10 in my CI, [python<3.11 failed](https://github.com/RichieHakim/ROICaT/actions/runs/11185453960). I will start on this unless I hear otherwise and I'll see how it goes.

**Issue 2: issues with pickling**
This is one of the several reasons why I wanted to move away from pickling entirely. I'll just reintroduce the .serializable_dict property for saving run_data using the pickle method

**Comment by RichieHakim** [comment]
You might also just be able to update filelock to >=3.15 or 3.16 for issue 1

**Comment by dyf** [comment]
I think you can just deprecate the legacy methods for (2). 

If adding 3.10 support is easy please do, but let me see about upgrading my environment to 3.11.

**Comment by RichieHakim** [comment]
I think I got it working. I'll push a quick fix in the next 5 minutes and keep working on it.

**Comment by RichieHakim** [comment]
Green lights: https://github.com/RichieHakim/ROICaT/actions/runs/11186422401/job/31101421045
[Merged](https://github.com/RichieHakim/ROICaT/pull/325) to main branch and pushed to pypi (v1.3.2)

**Comment by dyf** [comment]
Thank you! conda is still solving my environment, so you win.
