### ISSUE TITLE
Cuda not available on Windows (solved by conda install)

### ISSUE THREAD

**Issue by landoskape** [RichieHakim/ROICaT#69]
My initial installation of ROICaT did not have cuda available, even though I have it working in other environments on my machine. It's a Windows 10 computer, so maybe that's why (I haven't checked whether `pip install roicat[all]` configures cuda correctly on a mac or a linux). 

I solved this by using the standard _**conda**_ install command recommended on the [pytorch website](https://pytorch.org/get-started/locally/). Using conda makes sure the environment is configured correctly. For me, this looks like: 

```
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
```

**Comment by RichieHakim** [comment]
Above line of code now placed into READMe. See PR https://github.com/RichieHakim/ROICaT/pull/70
